#!/usr/bin/env sh

#  .oo.  .oo      88                            .o8                  o8o                     
# P'  `YP'       .8'                           "888                  `"'                     
#               .8'      oooo    ooo  .oooo.    888oooo.   .oooo.   oooo  oooo d8b  .ooooo.  
#              .8'        `88.  .8'  `P  )88b   d88' `88b `P  )88b  `888  `888""8P d88' `"Y8 
#             .8'          `88..8'    .oP"888   888   888  .oP"888   888   888     888       
#            .8'     .o.    `888'    d8(  888   888   888 d8(  888   888   888     888   .o8 
#            88      Y8P     .8'     `Y888""8o  `Y8bod8P' `Y888""8o o888o d888b    `Y8bod8P' 
#                        .o..P'                                                              
#                        `Y8P'                                                               

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                on
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.1
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.80
yabai -m config window_border                off
yabai -m config window_border_width          3
yabai -m config active_window_border_color   0xff775759
yabai -m config normal_window_border_color   0x00000000
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  5 
yabai -m config bottom_padding               8
yabai -m config left_padding                 5
yabai -m config right_padding                5
yabai -m config window_gap                   10

# Float windows
yabai -m rule --add app=Finder manage=off
yabai -m rule --add app=Spotify manage=off
yabai -m rule --add app=System\ Preferences manage=off
yabai -m rule --add app=Calculator manage=off
# yabai -m rule --add app= manage=off

echo "yabai configuration loaded.."
